//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZenCart.Fishbowl.SQL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ZenCart {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ZenCart() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZenCart.Fishbowl.SQL.ZenCart", typeof(ZenCart).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from orders_products
        ///where orders_id = &apos;{0}&apos;.
        /// </summary>
        internal static string ZenCart_GetOrder_Products {
            get {
                return ResourceManager.GetString("ZenCart_GetOrder_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select orders.* from orders
        ///left join fishbowl_imported on orders.orders_id = fishbowl_imported.orderid
        ///where fishbowl_imported.orderid is null .
        /// </summary>
        internal static string ZenCart_GetOrders {
            get {
                return ResourceManager.GetString("ZenCart_GetOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select products.productsid from products where products_model=&apos;@mdl&apos;.
        /// </summary>
        internal static string ZenCart_ProductExist {
            get {
                return ResourceManager.GetString("ZenCart_ProductExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO `massbeva_orders`.`fishbowl_imported` (`id`, `orderid`, `sonum`) VALUES (NULL, {0}, &apos;{1}&apos;);.
        /// </summary>
        internal static string ZenCart_ZC2FBDownloaded {
            get {
                return ResourceManager.GetString("ZenCart_ZC2FBDownloaded", resourceCulture);
            }
        }
    }
}
